# Generated by Django 4.2.8 on 2025-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Computer_Science',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='English',
        ),
    ]
