# Generated by Django 4.2.8 on 2024-01-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentDateNTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
