# Generated by Django 4.2.8 on 2024-01-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_paymentdatentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
