# Generated by Django 4.2.8 on 2025-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
