# Generated by Django 4.2.8 on 2025-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
