# Generated by Django 4.2.7 on 2023-12-31 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mathQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('subject', models.CharField(default='Mathematics', max_length=50)),
                ('q1', models.CharField(blank=True, max_length=100, null=True)),
                ('q2', models.CharField(blank=True, max_length=100, null=True)),
                ('q3', models.CharField(blank=True, max_length=100, null=True)),
                ('q4', models.CharField(blank=True, max_length=100, null=True)),
                ('q5', models.CharField(blank=True, max_length=100, null=True)),
                ('q6', models.CharField(blank=True, max_length=100, null=True)),
                ('q7', models.CharField(blank=True, max_length=100, null=True)),
                ('q8', models.CharField(blank=True, max_length=100, null=True)),
                ('quizTime', models.DateField(default=datetime.date.today)),
                ('correctAnswersCount', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('topicName', models.CharField(max_length=100)),
                ('questionNumber', models.CharField(default='0', max_length=100)),
                ('question', models.TextField()),
                ('nameTag', models.CharField(default=0, max_length=100)),
                ('correctAnswer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('topicName', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='Docs')),
                ('uploaded_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='scienceQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('subject', models.CharField(default='Science', max_length=50)),
                ('q1', models.CharField(blank=True, max_length=100, null=True)),
                ('q2', models.CharField(blank=True, max_length=100, null=True)),
                ('q3', models.CharField(blank=True, max_length=100, null=True)),
                ('q4', models.CharField(blank=True, max_length=100, null=True)),
                ('q5', models.CharField(blank=True, max_length=100, null=True)),
                ('q6', models.CharField(blank=True, max_length=100, null=True)),
                ('q7', models.CharField(blank=True, max_length=100, null=True)),
                ('q8', models.CharField(blank=True, max_length=100, null=True)),
                ('quizTime', models.DateField(default=datetime.date.today)),
                ('correctAnswersCount', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabusName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.syllabus')),
            ],
        ),
    ]
