# Generated by Django 4.2.9 on 2024-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_mathquizresult_id_remove_sciencequizresult_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathquizresult',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='sciencequizresult',
            name='test_id',
        ),
        migrations.AddField(
            model_name='mathquizresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sciencequizresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
