# Generated by Django 4.2.9 on 2024-01-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_mathquizresult_test_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=100)),
                ('blogAuthor', models.CharField(max_length=50)),
                ('blogUploadDate', models.DateField(default=datetime.date.today)),
                ('blogPara', models.TextField()),
            ],
        ),
    ]
