# Generated by Django 4.2.8 on 2024-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_blogs_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='gradeNumber',
            field=models.IntegerField(default=10),
        ),
    ]
