# Generated by Django 4.2.8 on 2024-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_fee_gradenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquizresult',
            name='q10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mathquizresult',
            name='q9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sciencequizresult',
            name='q10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sciencequizresult',
            name='q9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
