# Generated by Django 4.2.8 on 2024-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_mathquizresult_quiztime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquizresult',
            name='quizTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sciencequizresult',
            name='quizTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
