# Generated by Django 4.2.8 on 2024-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_alter_mathquizresult_quiztime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogImage',
            field=models.ImageField(max_length=1000, upload_to='media/blogs/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='document',
            field=models.FileField(upload_to='media/docs/'),
        ),
    ]
