# Generated by Django 4.2.8 on 2024-03-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_alter_blogs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='id',
            new_name='bid',
        ),
    ]
