# Generated by Django 4.2.8 on 2024-03-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_rename_id_blogs_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='bid',
            new_name='id',
        ),
    ]
