# Generated by Django 4.2.8 on 2024-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_rename_id_blogs_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/'),
        ),
    ]
