# Generated by Django 4.2.8 on 2024-03-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_quiz_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/quiz/'),
        ),
    ]
